---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ocp-virt-api-resource-collector
subjects:
  - kind: ServiceAccount
    name: api-resource-collector
    namespace: openshift-compliance
roleRef:
  kind: ClusterRole
  name: ocp-virt-api-resource-collector
  apiGroup: rbac.authorization.k8s.io
