apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: complianceremediation-editor-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - complianceremediations/status
  verbs:
  - get
