apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: compliancesuite-viewer-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancesuites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - compliancesuites/status
  verbs:
  - get
