apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rerunner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rerunner
subjects:
- kind: ServiceAccount
  name: rerunner
  namespace: openshift-compliance
