apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: scansettingbinding-editor-role
rules:
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compliance.openshift.io
  resources:
  - scansettingbindings/status
  verbs:
  - get
