#!/usr/bin/env bash
set -euo pipefail

TEST_OUTPUT="${1:?Usage: $0 <test-output-log> <output-baseline>}"
OUTPUT="${2:?Usage: $0 <test-output-log> <output-baseline>}"

if [ ! -f "$TEST_OUTPUT" ]; then
    echo "ERROR: Test output $TEST_OUTPUT not found."
    exit 1
fi

# Extract per-package coverage from go test output.
# Handles both plain and JSON (-json) formats:
#   plain: ok  	github.com/.../pkg	1.234s	coverage: 67.5% of statements
#   json:  {"Package":"github.com/.../pkg","Output":"coverage: 67.5% of statements\n"}
extract_coverage() {
    grep 'coverage:.*of statements' "$1" | while IFS= read -r line; do
        if [[ "$line" == "{"* ]]; then
            pkg=$(echo "$line" | sed 's/.*"Package":"\([^"]*\)".*/\1/')
        elif [[ "$line" == ok* ]]; then
            pkg=$(echo "$line" | awk '{print $2}')
        else
            continue
        fi
        pct=$(echo "$line" | sed 's/.*coverage: \([0-9.]*\)%.*/\1/')
        printf '%s\t%s\n' "$pkg" "$pct"
    done
}

{
    echo "# Coverage baseline for compliance-operator"
    echo "# Generated by: make update-coverage-baseline"
    echo "# Do not edit manually."
    extract_coverage "$TEST_OUTPUT" | sort
} > "$OUTPUT"

echo "Coverage baseline written to $OUTPUT:"
cat "$OUTPUT"
