#!/usr/bin/env bash
set -euo pipefail

TEST_OUTPUT="${1:?Usage: $0 <test-output-log> <output-baseline> <coverprofile>}"
OUTPUT="${2:?Usage: $0 <test-output-log> <output-baseline> <coverprofile>}"
COVERPROFILE="${3:?Usage: $0 <test-output-log> <output-baseline> <coverprofile>}"

if [ ! -f "$TEST_OUTPUT" ]; then
    echo "ERROR: Test output $TEST_OUTPUT not found."
    exit 1
fi

if [ ! -f "$COVERPROFILE" ]; then
    echo "ERROR: Coverprofile $COVERPROFILE not found."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Extract per-package coverage from go test output.
# Handles both plain and JSON (-json) formats:
#   plain: ok  	github.com/.../pkg	1.234s	coverage: 67.5% of statements
#   json:  {"Package":"github.com/.../pkg","Output":"coverage: 67.5% of statements\n"}
extract_coverage() {
    grep 'coverage:.*of statements' "$1" | while IFS= read -r line; do
        if [[ "$line" == "{"* ]]; then
            pkg=$(echo "$line" | sed 's/.*"Package":"\([^"]*\)".*/\1/')
        elif [[ "$line" == ok* ]]; then
            pkg=$(echo "$line" | awk '{print $2}')
        else
            continue
        fi
        pct=$(echo "$line" | sed 's/.*coverage: \([0-9.]*\)%.*/\1/')
        printf '%s\t%s\n' "$pkg" "$pct"
    done
}

# Compute per-package coverage from a coverprofile, excluding generated files.
extract_filtered_coverage() {
    local filtered
    filtered=$(mktemp)
    trap "rm -f $filtered" RETURN
    "${SCRIPT_DIR}/filter-coverage.sh" "$1" "$filtered"
    awk 'NR > 1 {
        split($1, a, ":")
        file = a[1]
        n = split(file, parts, "/")
        pkg = ""
        for (i = 1; i < n; i++) pkg = pkg (i > 1 ? "/" : "") parts[i]
        stmts = $2 + 0
        count = $3 + 0
        total[pkg] += stmts
        if (count > 0) covered[pkg] += stmts
    }
    END {
        for (pkg in total) {
            pct = (total[pkg] > 0) ? (covered[pkg] / total[pkg] * 100.0) : 0
            printf "%s\t%.1f\n", pkg, pct
        }
    }' "$filtered"
}

{
    echo "# Coverage baseline for compliance-operator"
    echo "# Generated by: make update-coverage-baseline"
    echo "# Do not edit manually."
    extract_filtered_coverage "$COVERPROFILE" | sort
} > "$OUTPUT"

echo "Coverage baseline written to $OUTPUT:"
cat "$OUTPUT"
