# bundle variant
# Adds namespace to all resources.
namespace: openshift-compliance

bases:
- ../manifests

patches:
- path: manager_patch.yaml
  target:
    kind: Deployment
    name: compliance-operator
- path: annotations.yaml
  target:
    kind: ClusterServiceVersion
    name: compliance-operator.vVERSION
- path: icon.yaml
  target:
    kind: ClusterServiceVersion
    name: compliance-operator.vVERSION
- path: images.yaml
  target:
    kind: ClusterServiceVersion
    name: compliance-operator.vVERSION
