apiVersion: compliance.openshift.io/v1alpha1
kind: ProfileBundle
metadata:
  name: ocp4
spec:
  contentImage: quay.io/compliance-operator/compliance-operator-content:latest
  contentFile: ssg-ocp4-ds.xml
