apiVersion: compliance.openshift.io/v1alpha1
kind: CustomRule
metadata:
  name: pods-must-have-security-context
  namespace: openshift-compliance
spec:
  description: Ensures all pods have a security context defined with runAsNonRoot set to true
  failureReason: Pod(s) found without proper security context (runAsNonRoot must be true)
  expression: |
    pods.items.all(pod,
      pod.spec.securityContext != null &&
      pod.spec.securityContext.runAsNonRoot == true
    )
  id: pods_must_have_security_context
  checkType: Platform
  inputs:
    - kubernetesInputSpec:
        apiVersion: v1
        resource: pods
      name: pods
  scannerType: CEL
  severity: high
  title: Pods Must Have Security Context
