name: Release latest

on:
  push:
    branches: ["master"]

jobs:
  # Build catalog from Konflux bundle
  # Operator, bundle, openscap, and must-gather images are built by Konflux
  catalog-container-push-pr:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: latest
      dockerfile_path: catalog.Dockerfile
      vendor: "Compliance Operator Authors"
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=quay.io/redhat-user-workloads/ocp-isc-tenant/compliance-operator-bundle-dev:master
      platforms: "linux/amd64,linux/ppc64le,linux/s390x,linux/arm64"
