name: Release

on:
  push:
    tags:
      - v**

jobs:
  prebuild-check:
    runs-on: ubuntu-latest
    # use matrix to run for multiple architectures
    strategy:
      matrix:
        arch: [linux/amd64, linux/ppc64le, linux/s390x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build container images and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/Dockerfile.prebuild
          tags: complianceascode/compliance-operator:${GITHUB_REF_NAME}-${{ matrix.arch }}
          push: false
          sbom: false
          platforms: ${{ matrix.arch }}
    
  container-main:
    needs:
      - prebuild-check
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: build/Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  openscap-container:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: openscap-ocp
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: images/openscap/Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  bundle-container:
    needs:
      - prebuild-check
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-bundle
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: bundle.Dockerfile
      vendor: "Compliance Operator Authors"
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"

  catalog-container-push-pr:
    needs:
      - prebuild-check
      - container-main
      - openscap-container
      - bundle-container
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: compliance-operator-catalog
      registry_org: complianceascode
      tag: ${GITHUB_REF_NAME}
      dockerfile_path: catalog.Dockerfile
      vendor: "Compliance Operator Authors"
      prepare_command: |
        make catalog-docker BUNDLE_IMGS=ghcr.io/complianceascode/compliance-operator-bundle:${GITHUB_REF_NAME}
      platforms: "linux/amd64,linux/ppc64le,linux/s390x"
